### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JAZzmiX** [Viber/sample-bot-isitup#3]
> TypeError: Data must be a string or a buffer
    at Hmac.update (crypto.js:97:16)
    at MessageValidator._calculateHmacFromMessage (/home/nowuser/src/node_modules/viber-bot/lib/message/message-validator.js:17:54)
    at MessageValidator.validateMessage (/home/nowuser/src/node_modules/viber-bot/lib/message/message-validator.js:11:30)
    at _app.use (/home/nowuser/src/node_modules/viber-bot/lib/middleware.js:61:32)
    at Layer.handle [as handle_request] (/home/nowuser/src/node_modules/viber-bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nowuser/src/node_modules/viber-bot/node_modules/express/lib/router/index.js:317:13)
    at /home/nowuser/src/node_modules/viber-bot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nowuser/src/node_modules/viber-bot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nowuser/src/node_modules/viber-bot/node_modules/express/lib/router/index.js:275:10)
    at textParser (/home/nowuser/src/node_modules/body-parser/lib/types/text.js:69:7)

**Comment by r-pr** [comment]
Had the same error when visiting url of bot, deployed to [now](https://isitup-bot-mnyavphlkp.now.sh/).

**Comment by 915210036** [comment]
Привет
